// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokerVideoGame.Api.Models;

#nullable disable

namespace PokerVideoGame.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231211074908_InitializePlayers")]
    partial class InitializePlayers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PokerVideoGame.Models.GameHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Prize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("GameHistories");
                });

            modelBuilder.Entity("PokerVideoGame.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountBalance")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountBalance = 1000,
                            Name = "Mikolaj"
                        },
                        new
                        {
                            Id = 2,
                            AccountBalance = 1000,
                            Name = "Bartosz"
                        },
                        new
                        {
                            Id = 3,
                            AccountBalance = 1000,
                            Name = "Kamil"
                        },
                        new
                        {
                            Id = 4,
                            AccountBalance = 1000,
                            Name = "Korneliusz"
                        },
                        new
                        {
                            Id = 5,
                            AccountBalance = 1000,
                            Name = "Amadeusz"
                        },
                        new
                        {
                            Id = 6,
                            AccountBalance = 1000,
                            Name = "Mateusz"
                        },
                        new
                        {
                            Id = 7,
                            AccountBalance = 1000,
                            Name = "Szymon"
                        });
                });

            modelBuilder.Entity("PokerVideoGame.Models.GameHistory", b =>
                {
                    b.HasOne("PokerVideoGame.Models.Player", null)
                        .WithMany("PlayerGameHistory")
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("PokerVideoGame.Models.Player", b =>
                {
                    b.Navigation("PlayerGameHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
